stages:
  - deploy

sync_to_gitee:
  stage: deploy
  image:
    name: docker.m.daocloud.io/alpine/git:2.45.2
    entrypoint: [""]
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - when: never
  script:
    - git --version
    - test -n "$REMOTE_USER"
    - test -n "$REMOTE_TOKEN"
    - git push --force "https://${REMOTE_USER}:${REMOTE_TOKEN}@gitee.com/HuangQijun0909/test.git" "HEAD:refs/heads/develop"
